### ISSUE TITLE
Rewritten Yaml nested parameters 

### ISSUE THREAD

**Issue by T-Lemmel** [open-navigation/navigation2#4308]
**Hello, i am trying to use Rewritten yaml inside a launch file for my nav2_parameters, as such :** 

![image](https://github.com/open-navigation/navigation2/assets/144454425/624e3e2b-021c-4ad9-b204-7b16c82b4ec1)

the robot_base_frame, global_frame and odom_topic are correctly assigned, but **not the nested ones**.
  
#### Expected behavior

```
$ ros2 param get /local_costmap/local_costmap obstacle_layer.scan.topic
String value is: robot_name/scan
```

#### Actual behavior

```
$ ros2 param get /local_costmap/local_costmap obstacle_layer.scan.topic
String value is: /scan
```

#### Additional information

i tried using the root_key argument, like that : 

![image](https://github.com/open-navigation/navigation2/assets/144454425/cb80dea1-9d6f-4fd7-8ebb-082dbad5fe0f)

**but then my others parameters are not assigned properly and i get this error :** 

[controller_server-8] [ERROR] [1715082825.036608858] [controller_server]: Couldn't load critics! Caught exception: No critics defined for FollowPath

**here is my the relevant part of my param file :** 
```

controller_server:
    ros__parameters:
      use_sim_time: False
      controller_frequency: 20.0
      min_x_velocity_threshold: 0.001
      min_y_velocity_threshold: 0.5
      min_theta_velocity_threshold: 0.001
      failure_tolerance: 0.3
      odom_topic: "odometry"
      scan.topic: "scan"
      progress_checker_plugin: "progress_checker"
      goal_checker_plugin: "goal_checker"
      controller_plugins: ["follow_path"]
     # Progress checker parameters
      progress_checker:
        plugin: "nav2_controller::SimpleProgressChecker"
        required_movement_radius: 0.5
        movement_time_allowance: 10.0
      # Goal checker parameters
      goal_checker:
        plugin: "nav2_controller::SimpleGoalChecker"
        xy_goal_tolerance: 0.25
        yaw_goal_tolerance: 0.25
        stateful: True
      # basic MPC with DWB
      follow_path:
        plugin: "dwb_core::DWBLocalPlanner"
        debug_trajectory_details: True
        min_vel_x: 0.0
        min_vel_y: 0.0
        max_vel_x: 0.26
        max_vel_y: 0.0
        max_vel_theta: 1.0
        min_speed_xy: 0.0
        max_speed_xy: 0.26
        min_speed_theta: 0.0
        acc_lim_x: 2.5
        acc_lim_y: 0.0
        acc_lim_theta: 3.2
        decel_lim_x: -2.5
        decel_lim_y: 0.0
        decel_lim_theta: -3.2
        vx_samples: 20
        vy_samples: 5
        vtheta_samples: 20
        sim_time: 1.7
        linear_granularity: 0.05
        angular_granularity: 0.025
        transform_tolerance: 0.2
        xy_goal_tolerance: 0.25
        trans_stopped_velocity: 0.25
        short_circuit_trajectory_evaluation: True
        stateful: True
        critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
        BaseObstacle.scale: 0.2
        PathAlign.scale: 32.0
        PathAlign.forward_point_distance: 0.1
        GoalAlign.scale: 24.0
        GoalAlign.forward_point_distance: 0.1
        PathDist.scale: 32.0
        GoalDist.scale: 24.0
        RotateToGoal.scale: 32.0
        RotateToGoal.slowing_factor: 5.0
        RotateToGoal.lookahead_time: -1.0

```
Does anyone have an idea ? 
Thanks in advance,
Tom

Ps : using ubuntu 22.04 and ros2 humble
